# Generated by Django 4.2.13 on 2024-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'The Question', 'verbose_name_plural': 'Peoples Questions'},
        ),
    ]
